In [203]:
import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn import preprocessing
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [204]:
df = pd.read_csv('F:/Course Study/Thesis(Musharrat Mam)/iris_data.csv')
df

sepalLength  sepalWidth  petalLength  petalWidth           class
0            5.1         3.5          1.4         0.2     Iris-setosa
1            4.9         3.0          1.4         0.2     Iris-setosa
2            4.7         3.2          1.3         0.2     Iris-setosa
3            4.6         3.1          1.5         0.2     Iris-setosa
4            5.0         3.6          1.4         0.2     Iris-setosa
..           ...         ...          ...         ...             ...
145          6.7         3.0          5.2         2.3  Iris-virginica
146          6.3         2.5          5.0         1.9  Iris-virginica
147          6.5         3.0          5.2         2.0  Iris-virginica
148          6.2         3.4          5.4         2.3  Iris-virginica
149          5.9         3.0          5.1         1.8  Iris-virginica

[150 rows x 5 columns]

In [205]:
print(df['class'].unique())
df.loc[df['class']=='Iris-setosa', 'class'] = 0
df.loc[df['class']=='Iris-versicolor', 'class'] = 2
df.loc[df['class']=='Iris-virginica', 'class'] = 1
print(df['class'].unique())

['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
[0 2 1]


In [206]:
df_1=df.iloc[0:35,]
df_4=df.iloc[35:50,]
df_2=df.iloc[50:85,]
df_5=df.iloc[85:100,]
df_3=df.iloc[100:135,]
df_6=df.iloc[135:150,]

In [207]:
df_train=pd.concat([df_1, df_2, df_3])
df_test=pd.concat([df_4, df_5, df_6])


In [208]:
len(df_test)

45

In [209]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(df_train.drop(['class'],axis=1))
predictions=kmeans.predict(df_test.drop(['class'],axis= 1))

In [210]:
predictions

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1,
       2])

In [211]:
score = accuracy_score(df_test['class'], predictions)
score

0.9111111111111111

In [212]:
print(classification_report(df_test['class'], predictions)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      0.73      0.85        15
           2       0.79      1.00      0.88        15

    accuracy                           0.91        45
   macro avg       0.93      0.91      0.91        45
weighted avg       0.93      0.91      0.91        45



### Normalizing

In [179]:
df_drop = df.drop(['class'],axis = 1)
df_drop

sepalLength  sepalWidth  petalLength  petalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [180]:
mn=preprocessing.MinMaxScaler()
x_norm =mn.fit_transform(df_drop)

In [181]:
x_norm

array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [182]:
dataset = pd.DataFrame({'sepalLength': x_norm[:, 0], 'sepalWidth': x_norm[:, 1], 'petalLength': x_norm[:, 2], 'petalWidth': x_norm[:, 3]})

In [183]:
dataset

sepalLength  sepalWidth  petalLength  petalWidth
0       0.222222    0.625000     0.067797    0.041667
1       0.166667    0.416667     0.067797    0.041667
2       0.111111    0.500000     0.050847    0.041667
3       0.083333    0.458333     0.084746    0.041667
4       0.194444    0.666667     0.067797    0.041667
..           ...         ...          ...         ...
145     0.666667    0.416667     0.711864    0.916667
146     0.555556    0.208333     0.677966    0.750000
147     0.611111    0.416667     0.711864    0.791667
148     0.527778    0.583333     0.745763    0.916667
149     0.444444    0.416667     0.694915    0.708333

[150 rows x 4 columns]

In [184]:
dataset_1=dataset.iloc[0:35,]
dataset_4=dataset.iloc[35:50,]
dataset_2=dataset.iloc[50:85,]
dataset_5=dataset.iloc[85:100,]
dataset_3=dataset.iloc[100:135,]
dataset_6=dataset.iloc[135:150,]

In [185]:
data_train=pd.concat([dataset_1, dataset_2, dataset_3])
data_test=pd.concat([dataset_4, dataset_5, dataset_6])

In [186]:
data_test

sepalLength  sepalWidth  petalLength  petalWidth
35      0.194444    0.500000     0.033898    0.041667
36      0.333333    0.625000     0.050847    0.041667
37      0.166667    0.458333     0.084746    0.000000
38      0.027778    0.416667     0.050847    0.041667
39      0.222222    0.583333     0.084746    0.041667
40      0.194444    0.625000     0.050847    0.083333
41      0.055556    0.125000     0.050847    0.083333
42      0.027778    0.500000     0.050847    0.041667
43      0.194444    0.625000     0.101695    0.208333
44      0.222222    0.750000     0.152542    0.125000
45      0.138889    0.416667     0.067797    0.083333
46      0.222222    0.750000     0.101695    0.041667
47      0.083333    0.500000     0.067797    0.041667
48      0.277778    0.708333     0.084746    0.041667
49      0.194444    0.541667     0.067797    0.041667
85      0.472222    0.583333     0.593220    0.625000
86      0.666667    0.458333     0.627119    0.583333
87      0.555556    0.125000     0.576271    0.500000
88      0.361111    0.416667     0.525424    0.500000
89      0.333333    0.208333     0.508475    0.500000
90      0.333333    0.250000     0.576271    0.458333
91      0.500000    0.416667     0.610169    0.541667
92      0.416667    0.250000     0.508475    0.458333
93      0.194444    0.125000     0.389831    0.375000
94      0.361111    0.291667     0.542373    0.500000
95      0.388889    0.416667     0.542373    0.458333
96      0.388889    0.375000     0.542373    0.500000
97      0.527778    0.375000     0.559322    0.500000
98      0.222222    0.208333     0.338983    0.416667
99      0.388889    0.333333     0.525424    0.500000
135     0.944444    0.416667     0.864407    0.916667
136     0.555556    0.583333     0.779661    0.958333
137     0.583333    0.458333     0.762712    0.708333
138     0.472222    0.416667     0.644068    0.708333
139     0.722222    0.458333     0.745763    0.833333
140     0.666667    0.458333     0.779661    0.958333
141     0.722222    0.458333     0.694915    0.916667
142     0.416667    0.291667     0.694915    0.750000
143     0.694444    0.500000     0.830508    0.916667
144     0.666667    0.541667     0.796610    1.000000
145     0.666667    0.416667     0.711864    0.916667
146     0.555556    0.208333     0.677966    0.750000
147     0.611111    0.416667     0.711864    0.791667
148     0.527778    0.583333     0.745763    0.916667
149     0.444444    0.416667     0.694915    0.708333

In [187]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(data_train)

In [188]:
predictions=kmeans.predict(data_test)
score = accuracy_score(df_test['class'], predictions)
score

0.9111111111111111

In [190]:
print(classification_report(df_test['class'], predictions)) 

              precision    recall  f1-score   support

           0       1.00      0.73      0.85        15
           1       1.00      1.00      1.00        15
           2       0.79      1.00      0.88        15

    accuracy                           0.91        45
   macro avg       0.93      0.91      0.91        45
weighted avg       0.93      0.91      0.91        45



### Scaling

In [121]:
df_drop

sepalLength  sepalWidth  petalLength  petalWidth
0            5.1         3.5          1.4         0.2
1            4.9         3.0          1.4         0.2
2            4.7         3.2          1.3         0.2
3            4.6         3.1          1.5         0.2
4            5.0         3.6          1.4         0.2
..           ...         ...          ...         ...
145          6.7         3.0          5.2         2.3
146          6.3         2.5          5.0         1.9
147          6.5         3.0          5.2         2.0
148          6.2         3.4          5.4         2.3
149          5.9         3.0          5.1         1.8

[150 rows x 4 columns]

In [122]:
mn=preprocessing.StandardScaler()
x_stand =mn.fit_transform(df_drop)

In [123]:
d_1 = pd.DataFrame({'sepalLength': x_stand[:, 0], 'sepalWidth': x_stand[:, 1], 'petalLength': x_stand[:, 2], 'petalWidth': x_stand[:, 3]})

In [124]:
data_1=d_1.iloc[0:35,]
data_4=d_1.iloc[35:50,]
data_2=d_1.iloc[50:85,]
data_5=d_1.iloc[85:100,]
data_3=d_1.iloc[100:135,]
data_6=d_1.iloc[135:150,]

In [125]:
d_train=pd.concat([data_1, data_2, data_3])
d_test=pd.concat([data_4, data_5, data_6])

In [126]:
kmeans = KMeans(n_clusters=3, random_state=0).fit(d_train)

In [127]:
predictions=kmeans.predict(d_test)
predictions

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       0])

In [128]:
score = accuracy_score(df_test['class'], predictions)
score

0.8666666666666667

In [130]:
print(classification_report(df_test['class'], predictions)) 

              precision    recall  f1-score   support

           0       0.76      0.87      0.81        15
           1       0.85      0.73      0.79        15
           2       1.00      1.00      1.00        15

    accuracy                           0.87        45
   macro avg       0.87      0.87      0.87        45
weighted avg       0.87      0.87      0.87        45

